[package]
name = "keyboard_layout"
version = "0.1.0"
edition = "2021"

[dependencies]
wayfire-rs = { path = "../.." }                  # Points to root Cargo.toml
tokio = { version = "1.0", features = ["full"] }
